=== Lonely-Taco/JabberPoint_Refactored/jabberpoint.dtd
<!--
 Document Type Definition voor JabberPoint presentations
 $Id$
 -->
<!ELEMENT showtitle (#PCDATA)>
<!ELEMENT presentation (showtitle,slide+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT slide (title, item*)>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item kind CDATA #REQUIRED>
<!ATTLIST item level CDATA #REQUIRED>

=== Lonely-Taco/JabberPoint_Refactored/demoPresentation.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
    <showtitle>Demo Presentation</showtitle>
    <slide>
        <title>JabberPoint</title>
        <item kind="text" level="level1">The Java prestentation tool</item>
        <item kind="text" level="level2">Copyright (c) 1996-2000: Ian Darwin</item>
        <item kind="text" level="level2">Copyright (c) 2000-now:</item>
        <item kind="text" level="level2">Gert Florijn and Sylvia Stuurman</item>
        <item kind="text" level="level4">Calling Jabberpoint without a filename</item>
        <item kind="text" level="level4">will show this presentation</item>
        <item kind="text" level="level1">Navigate:</item>
        <item kind="text" level="level3">Next slide: PgDn or Enter</item>
        <item kind="text" level="level3">Previous slide: PgUp or up-arrow</item>
        <item kind="text" level="level3">Quit: q or Q</item>
    </slide>
    <slide>
        <title>Demonstration of levels and styles</title>
        <item kind="text" level="level1">Level 1</item>
        <item kind="text" level="level2">Level 2</item>
        <item kind="text" level="level1">Again level 1</item>
        <item kind="text" level="level1">Level 1 has style number 1</item>
        <item kind="text" level="level2">Level 2 has style number 2</item>
        <item kind="text" level="level3">This is how level 3 looks like</item>
        <item kind="text" level="level4">And this is level 4</item>
    </slide>
    <slide>
        <title>The third slide</title>
        <item kind="text" level="level1">To open a new presentation,</item>
        <item kind="text" level="level2">use File->Open from the menu.</item>
        <item kind="text" level="level1"> </item>
        <item kind="text" level="level1">This is the end of the presentation.</item>
        <item kind="image" level="level1">JabberPoint.jpg</item>
    </slide>
</presentation>

=== Lonely-Taco/JabberPoint_Refactored/testPresentation.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
	<showtitle>XML-Based Presentation for Jabberpoint</showtitle>
	<slide>
		<title>JabberPoint XML-Demo</title>
		<item kind="text"  level="level1">Welcome to JabberPoint</item>
		<item kind="text"  level="level2">Copyright (c) 1996-2000 Ian Darwin</item>
		<item kind="text"  level="level2">Rewritten by</item>
		<item kind="text"  level="level2">Gert Florijn, Mark van Elswijk, Marc Evers</item>
		<item kind="text"  level="level2">and Sylvia Stuurman</item>
		<item kind="text"  level="level1">Navigation:</item>
		<item kind="text"  level="level2">Next slide: PgDn or Enter</item>
		<item kind="text"  level="level2">Previous slide: PgUp or up-arrow</item>
		<item kind="text"  level="level2">Quit: q or Q</item>
	</slide>
	<slide>
		<title>An almost empty slide</title>
		<item kind="text"  level="level1"> </item>
	</slide>
	<slide>
		<title>Background</title>
		<item kind="text"  level="level1">Jabberpoint is originally an exercise for the</item>
		<item kind="text"  level="level1">course Design patterns of the Open university</item>
		<item kind="text"  level="level1">but is also used for the course OO1 of the NHL-Stenden university of applied sciences</item>
		<item kind="text"  level="level1"> </item>
		<item kind="image"  level="level2">logo-woordmerk_ou.gif</item>
		<item kind="image"  level="level2">logo_nhlstenden.jpg</item>
		<item kind="text"  level="level1"> </item>
		<item kind="text"  level="level1">The exercise is developed by the SERC</item>
		<item kind="text"  level="level1">in collaboration with the Open university </item>
		<item kind="text"  level="level1"> </item>
		<item kind="image"  level="level2">serclogo_fc.jpg</item>
	</slide>
	<slide>
		<title>JabberPoint: Levels and styles</title>
		<item kind="text"  level="level1">Level 1</item>
		<item kind="text"  level="level2">Level 2</item>
		<item kind="text"  level="level1">A Jabberful Point</item>
		<item kind="text"  level="level2">Level 2 has style 2</item>
		<item kind="text"  level="level3">This is the style of level 3</item>
		<item kind="text"  level="level4">And this level 4</item>
	</slide>
	<slide>
		<title>Last slide</title>
		<item kind="text"  level="level1">Navigation can also be done via the menu</item>
		<item kind="text"  level="level2">Load a presentation: File->Open</item>
		<item kind="text"  level="level1"> </item>
		<item kind="text"  level="level1">This is the end of the presentation.</item>
		<item kind="image"  level="level1">JabberPoint.jpg</item>
		<item kind="text"  level="level1">Goodbye.</item>
	</slide>
</presentation>
